<?php namespace App\Constant;

class Permission {
	const VIEW_REPORT_SALE_SUMMARY = 2;
	
	const VIEW_CASH_ACCOUNT = 5;
	const CREATE_CASH_ACCOUNT = 6;
	const UPDATE_CASH_ACCOUNT = 7;
	const CASHFLOW_HISTORY = 8;

	const VIEW_PERMISSION = 10;
	const CREATE_PERMISSION = 11;
	const UPDATE_PERMISSION = 12;

	const VIEW_ROLE = 14;
	const CREATE_ROLE = 15;
	const UPDATE_ROLE = 16;

	const VIEW_USER = 18;
	const CREATE_USER = 19;
	const UPDATE_USER = 20;

	const VIEW_PRODUCT = 22;
	const CREATE_PRODUCT = 23;
	const UPDATE_PRODUCT = 24;

	const VIEW_CATEGORY = 26;
	const CREATE_CATEGORY = 27;
	const UPDATE_CATEGORY = 28;

	const VIEW_SHELF = 30;
	const CREATE_SHELF = 31;
	const UPDATE_SHELF = 32;

	const VIEW_SUPPLIER = 34;
	const CREATE_SUPPLIER = 35;
	const UPDATE_SUPPLIER = 36;

	const VIEW_ORDER_INVOICE = 38;
	const CREATE_ORDER_INVOICE = 39;
	const UPDATE_ORDER_INVOICE = 40;
	const DELETE_ORDER_INVOICE = 41;

	const VIEW_PURCHASE_INVOICE = 43;
	const CREATE_PURCHASE_INVOICE = 44;
	const UPDATE_PURCHASE_INVOICE = 45;
	const DELETE_PURCHASE_INVOICE = 46;

	const VIEW_CUSTOMER = 48;
	const CREATE_CUSTOMER = 49;
	const UPDATE_DELETE_CUSTOMER = 50;

	const VIEW_TRANSACTION = 52;
	const CREATE_TRANSACTION = 53;
	const UPDATE_TRANSACTION = 54;

	const VIEW_TRANSACTION_REPORT = 56;
	const VIEW_ACCOUNT_REPORT = 55;
}