<?php namespace App\Constant;

class Permission {
	const VIEW_REPORT_SALE_SUMMARY = 2;
	const VIEW_TOP_PRODUCT = 3;
	const VIEW_LOWEST_PRODUCT = 4;
	const FILTER_DASHBOARD_SUMMARY = 5;
	
	const VIEW_CASH_ACCOUNT = 7;
	const CREATE_CASH_ACCOUNT = 8;
	const UPDATE_CASH_ACCOUNT = 9;

	const VIEW_PERMISSION = 11;
	const CREATE_PERMISSION = 12;
	const UPDATE_PERMISSION = 13;

	const VIEW_ROLE = 15;
	const CREATE_ROLE = 16;
	const UPDATE_ROLE = 17;

	const VIEW_USER = 19;
	const CREATE_USER = 20;
	const UPDATE_USER = 21;
	const CHANGE_PASSWORD = 22;

	const VIEW_PRODUCT = 24;
	const SEARCH_PRODUCT = 25;
	const CREATE_PRODUCT = 26;
	const UPDATE_PRODUCT = 27;
	const CONFIGURE_PRICE = 28;

	const VIEW_CATEGORY = 30;
	const CREATE_CATEGORY = 31;
	const UPDATE_CATEGORY = 32;

	const VIEW_SHELF = 34;
	const CREATE_SHELF = 35;
	const UPDATE_SHELF = 36;

	const VIEW_SUPPLIER = 38;
	const CREATE_SUPPLIER = 39;
	const UPDATE_SUPPLIER = 40;

	const VIEW_ORDER_INVOICE = 42;
	const CREATE_ORDER_INVOICE = 43;
	const UPDATE_ORDER_INVOICE = 44;
	const CANCEL_ORDER_INVOICE = 45;
	const PRINT_ORDER_INVOICE = 46;

	const VIEW_PURCHASE_INVOICE = 48;
	const CREATE_PURCHASE_INVOICE = 49;
	const UPDATE_PURCHASE_INVOICE = 50;

	const VIEW_TRANSACTION = 57;
	const CREATE_TRANSACTION = 58;
	const UPDATE_TRANSACTION = 59;
	const VIEW_TODAY_TRANSACTION_SUMMARY = 60;
	const FILTER_TRANSACTION = 61;
	const DOWNLOAD_TRANSACTION_REPORT = 62;

	const CREATE_DEBT = 64;
	const VIEW_DEBT = 65;
	const UPDATE_DEBT = 66;
	const SEARCH_DEBT = 67;

	const CREATE_RECEIVABLE = 83;
	const VIEW_RECEIVABLE = 82;
	const UPDATE_RECEIVABLE = 84;

	const VIEW_CUSTOMER = 52;
	const CREATE_CUSTOMER = 53;
	const UPDATE_CUSTOMER = 54;
	const SEARCH_CUSTOMER = 55;

	
	const VIEW_STOCK_PRODUCT = 69;
	const FILTER_STOCK_PRODUCT = 70;
	const DOWNLOAD_STOCK_PRODUCT = 71;
	const VIEW_STOCK_PRODUCT_ACTIVITY = 72;
	const DOWNLOAD_STOCK_PRODUCT_ACTIVITY = 73;
	const FILTER_STOCK_PRODUCT_ACTIVITY = 74;

	const VIEW_ACCOUNT_REPORT = 75;
	const FILTER_ACCOUNT_REPORT = 76;
	const DOWNLOAD_ACCOUNT_REPORT = 77;
	const VIEW_ACCOUNT_ACTIVITY = 78;
	const FILTER_ACCOUNT_ACTIVITY = 79;
	const DOWNLOAD_ACCOUNT_ACTIVITY = 80;
}